conky.config = {
    alignment = 'top_middle',
    gap_x = 0,
    gap_y = 80,

    own_window = true,
    own_window_type = 'desktop',
    own_window_argb_visual = true,
    own_window_argb_value = 0,

    background = false,
    double_buffer = true,
    use_xft = true,

    draw_shades = false,
    draw_outline = false,
    draw_borders = false,

    minimum_width = 500,
    minimum_height = 100,

    default_color = 'FFFFFF',
    update_interval = 1,
};

conky.text = [[
${alignc}${font Anurati:size=42}${execi 60 date +%A | tr '[:lower:]' '[:upper:]'}${font}

${alignc}${font JetBrains Mono:size=16}${time %d %B %Y}

${alignc}${font JetBrains Mono:size=18}${time %I:%M %p}
]];
