conky.config = {
    alignment = 'top_right',
    gap_x = 35,
    gap_y = 80,

    own_window = true,
    own_window_type = 'desktop',
    own_window_argb_visual = true,
    own_window_argb_value = 0,

    background = false,
    double_buffer = true,
    use_xft = true,

    draw_shades = false,
    draw_outline = false,
    draw_borders = false,

    minimum_width = 220,
    minimum_height = 160,

    default_color = 'FFFFFF',
    update_interval = 2,
};

conky.text = [[
${font JetBrains Mono Bold:size=12}SYSTEM${font}

${font JetBrains Mono:size=11}CPU      ${alignr}${cpu cpu0}%
${cpubar cpu0 4,140}

RAM      ${alignr}$memperc%
${membar 4,140}

TEMP     ${alignr}${hwmon 4 temp 1}°C

FAN      ${alignr}${execi 2 sensors | awk '/Processor Fan/ {print $3}'} RPM
]];
